/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import cineMarcus.Filme;
import cineMarcus.FilmeController;
import cineMarcus.SessaoController;
import java.awt.Cursor;
import java.awt.Dimension;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ruan
 */
public class PainelDoAdmin extends javax.swing.JFrame {

    private final FilmeController filmeController;
    private final SessaoController sessaoController;
    private final List<Filme> listaFilmes;

    
    public PainelDoAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        filmeController = FilmeController.getInstance();
        sessaoController = SessaoController.getInstance();
        listaFilmes = filmeController.getFilmes().parallelStream().collect(Collectors.toList());
        carregarFilmes();

    }
    
        public void carregarFilmes(){
        pnlFilmes.removeAll();
        
        for (int i = 0; i < listaFilmes.size(); i++) {          
            Filme filme = listaFilmes.get(i);

            int x = 25 + (167 * (i / 2));
            int y = 25 + (165 * (i % 2));
            
            JLabel labelFilme = new JLabel();
            PainelDoAdmin self = this;
            labelFilme.setIcon(new ImageIcon(filme.getPoster()));
            
            //labelFilme.addMouseListener(new java.awt.event.MouseAdapter() {
                //@Override
                //public void mouseClicked(java.awt.event.MouseEvent evt) {
                 //   new PainelDoAdmin(filme, self).setVisible(true);
                //}
            //});
            
            labelFilme.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            labelFilme.setBounds(x, y, 117, 150);
            pnlFilmes.add(labelFilme);
            
            if (i == listaFilmes.size() - 1) {
                pnlFilmes.setPreferredSize(new Dimension(x + 132, 409));
            }
            
            pnlFilmes.revalidate();
            pnlFilmes.repaint();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginImgLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnCF = new javax.swing.JButton();
        BtnCS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LoginImgLogo1 = new javax.swing.JLabel();
        pnlFilmes = new javax.swing.JScrollPane();

        LoginImgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnCF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camera.png"))); // NOI18N
        BtnCF.setText("   Cadastrar Filme");
        BtnCF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCFMouseExited(evt);
            }
        });
        BtnCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCFActionPerformed(evt);
            }
        });

        BtnCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cinema.png"))); // NOI18N
        BtnCS.setText("      Cadastrar Sessão");
        BtnCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCSMouseExited(evt);
            }
        });
        BtnCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCSActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Admin - Cadastros");

        LoginImgLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginImgLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        pnlFilmes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFilmes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnlFilmes))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(BtnCS, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123)
                            .addComponent(BtnCF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(LoginImgLogo1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginImgLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(pnlFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        BtnCF.getAccessibleContext().setAccessibleDescription("");
        BtnCF.getAccessibleContext().setAccessibleParent(BtnCF);
        BtnCS.getAccessibleContext().setAccessibleParent(BtnCS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCFActionPerformed
        new CadastroDeFilme().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCFActionPerformed

    private void BtnCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCSActionPerformed
        new CadastroDeSessao().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCSActionPerformed

    private void BtnCFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCFMouseEntered
        BtnCF.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_BtnCFMouseEntered

    private void BtnCFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCFMouseExited
        BtnCF.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnCFMouseExited

    private void BtnCSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCSMouseEntered
        BtnCS.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_BtnCSMouseEntered

    private void BtnCSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCSMouseExited
        BtnCS.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnCSMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelDoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelDoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelDoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelDoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelDoAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCF;
    private javax.swing.JButton BtnCS;
    private javax.swing.JLabel LoginImgLogo;
    private javax.swing.JLabel LoginImgLogo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane pnlFilmes;
    // End of variables declaration//GEN-END:variables
}
