/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import cineMarcus.Cliente;
import cineMarcus.FilmeController;
import cineMarcus.Login;
import cineMarcus.Sessao;
import cineMarcus.SessaoController;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.Document;

/**
 *
 * @author Bruno
 */
public class TelaCompra extends javax.swing.JFrame {
    private final String assentos;
    private final TelaFilme telafilme;
    private final Cliente user;
    private final List<Sessao> listaSessoes;
    private final SessaoController sessaoController;
    private final FilmeController filmeController;
    private final Sessao sessao;
    private final int quantidade;
    private final Login login;
    private Double val;
    /**
     * Creates new form TelaCompra
     */
    public TelaCompra(TelaFilme telafilme, String assentos, int sessaoID, int quantidade) {
        this.val=0.0;
        this.assentos=assentos;
        this.telafilme = telafilme;
        this.quantidade= quantidade;
        this.login = Login.getInstance();
        
        initComponents();
        sessaoController = SessaoController.getInstance();
        filmeController = FilmeController.getInstance();
        this.listaSessoes = sessaoController.getSessoes().parallelStream().collect(Collectors.toList());
        this.sessao = listaSessoes.get(sessaoID);
        user = (Cliente) Login.getInstance().getUsuarioLogado();
        carregarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void carregarInfo(){
        txtAssento.setText(assentos);
        this.val = sessao.getPreco()*quantidade;
        if(user.getNomeDeUsuario().equals("Marcus")){
            // Desconto de 10 por cento
            this.val *= 0.90;
            JOptionPane.showMessageDialog(null, "Parabéns, Marcus, você ganhou 10% de desconto!");
        }
        txtPreco.setText(Double.toString(this.val));
        txtSala.setText(Integer.toString(sessao.getSala()));
        txtQtd.setText(Integer.toString(quantidade));
        lblFilme.setText(filmeController.get(sessao.getFilmeId()).getNome());
        txtPrecoInd.setText(Double.toString(sessao.getPreco()));
        txtSaldo.setText(Float.toString(user.getDinheiro()));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFilme = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        txtAssento = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrecoInd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Preço Total");

        jLabel2.setText("Quantidade de Ingressos");

        jLabel3.setText("Assentos");

        jLabel4.setText("Sala");

        lblFilme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFilme.setText("Filme");

        txtSala.setEditable(false);
        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        txtAssento.setEditable(false);
        txtAssento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssentoActionPerformed(evt);
            }
        });

        txtQtd.setEditable(false);
        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });

        txtPreco.setEditable(false);

        btnFinalizar.setText("Finalizar Compra");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço por ingresso");

        txtPrecoInd.setEditable(false);

        jLabel6.setText("Saldo Atual");

        txtSaldo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecoInd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSaldo)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilme)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecoInd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void txtAssentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssentoActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if(user.getDinheiro() < this.val){
            JOptionPane.showMessageDialog(null, "Saldo insuficiente :c", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            user.setDinheiro((float)(user.getDinheiro()-this.val));
            ArrayList<Boolean> lista = (ArrayList<Boolean>) telafilme.listaSelected;
            ArrayList<Boolean> lista2 = (ArrayList<Boolean>) sessao.getAssentos();
            for(int i=0;i<lista.size();i++){
                if(lista.get(i)){
                    lista2.set(i, true);
                }
            }
            sessao.setAssentos(lista2);
            login.salvarJson();
            sessaoController.salvarJson();
            if(user.getIdade()< filmeController.get(sessao.getFilmeId()).getClassificacao()){
                JOptionPane.showMessageDialog(null, "Para entrar na sessão, apareça com um responsável", "Idade fora da Classificação Indicativa", JOptionPane.WARNING_MESSAGE);
            }
            
            
            
            JFrame parentComponent = new JFrame();
            JFileChooser fileChooser= new JFileChooser();
            // Some init code, if you need one, like setting title
            int returnVal = fileChooser.showOpenDialog(parentComponent);
            if ( returnVal == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                try{
                    
                    FileWriter fileWriter = new FileWriter(fileToSave);
                    PrintWriter printWriter = new PrintWriter(fileWriter);                 
                    printWriter.printf("Filme: %s\n", filmeController.get(sessao.getFilmeId()).getNome());
                    printWriter.printf("Assentos: %s\n", assentos);
                    printWriter.printf("Sala: %d\n", sessao.getSala());
                    printWriter.printf("Horario: %s\n", sessao.getData());
                    printWriter.printf("Quantidade De Ingressos: %d\n", quantidade);
                    printWriter.close();
                    
                    JOptionPane.showMessageDialog(null, "Ingresso salvo");
                    
                    JOptionPane.showMessageDialog(null, "Compra concluída, aproveite!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
            
            
            dispose();
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFilme;
    private javax.swing.JTextField txtAssento;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPrecoInd;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
