/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import cineMarcus.Filme;
import cineMarcus.Sessao;
import cineMarcus.SessaoController;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */

public class TelaFilme extends javax.swing.JFrame {
    private final List<Sessao> listaSessoes;
    private final SessaoController sessaoController;
    public final List<Boolean> listaSelected;

    
    private final Filme filme;
    /**
     * Creates new form TelaFilme
     * @param filme
     */
    public TelaFilme(Filme filme, TelaCinema cine) {
        initComponents();
        setLocationRelativeTo(null);
        this.filme = filme;
        sessaoController = SessaoController.getInstance();
        listaSelected = new ArrayList<Boolean>(Collections.nCopies(90, false));
        this.listaSessoes = sessaoController.getSessoes().parallelStream().collect(Collectors.toList());
        carregaPoster();
        carregaLabels();
        btnComprar.setVisible(false);
    }
    
    public String transformaAssento(int idx){
        // 6
        int y = (idx/15)+1;
        int x = idx%15;
        
        if(idx%15==0){
            x=15;
            y-=1;
        }
        
        return (char)('@'+y)+Integer.toString(x);
    }
    
    
    public void carregaLabels(){
        lblFilme.removeAll();
        lblFilme.setText(filme.getNome());
        
        txtSinopse.removeAll();
        txtSinopse.setText(filme.getSinopse());
        
        txtGenero.removeAll();
        txtGenero.setText(filme.getGenero());
        
        txtClass.removeAll();
        txtClass.setText(Integer.toString(filme.getClassificacao()));
        
        cmbSessoes.removeAllItems();
        cmbSessoes.addItem("Selecione uma Sessão");
        for (int i = 0; i < listaSessoes.size(); i++) {
            if(Objects.equals(listaSessoes.get(i).getFilmeId(), filme.getId())){
                cmbSessoes.addItem((listaSessoes.get(i).getData()));
            }
            
        }
    }
    public void carregaPoster(){
            JLabel labelFilme = new JLabel();
            labelFilme.setIcon(new ImageIcon(filme.getPoster()));
            labelFilme.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            labelFilme.setBounds(550, 100, 130, 190);
            pnlFilmes.add(labelFilme);
            
            pnlFilmes.revalidate();
            pnlFilmes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void trocarAssento(JLabel assento, int idx){
        String imagem = "";
        if(listaSelected.get(idx)){
            
            assento.setIcon(new ImageIcon("src/imagens/assentoazul.png"));
            listaSelected.set(idx, false);
        }else{
            assento.setIcon(new ImageIcon("src/imagens/assentolaranja.png"));
            listaSelected.set(idx, true);
        }
    } 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        pnlFilmes = new javax.swing.JPanel();
        lblFilme = new javax.swing.JLabel();
        cmbSessoes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopse = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        pnlSessao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        checkDub = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlAssentos = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        COFimgLogo = new javax.swing.JLabel();
        btnVoltar1 = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CineMarcus - Sobre o filme/ Seleção de assentos");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());

        pnlFilmes.setBackground(new java.awt.Color(255, 255, 255));

        lblFilme.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblFilme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFilme.setText("Filme");

        cmbSessoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Sinopse:");

        txtSinopse.setEditable(false);
        txtSinopse.setColumns(20);
        txtSinopse.setRows(5);
        jScrollPane1.setViewportView(txtSinopse);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Genero:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Classificação:");

        txtGenero.setEditable(false);
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        txtClass.setEditable(false);
        txtClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassActionPerformed(evt);
            }
        });

        pnlSessao.setBackground(new java.awt.Color(255, 255, 255));
        pnlSessao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Preço:");

        txtPreco.setEditable(false);
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Data:");

        txtData.setEditable(false);
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Sala:");

        txtSala.setEditable(false);
        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        checkDub.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        checkDub.setContentAreaFilled(false);
        checkDub.setEnabled(false);
        checkDub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDubActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Assentos");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Dublado");

        pnlAssentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlAssentosLayout = new javax.swing.GroupLayout(pnlAssentos);
        pnlAssentos.setLayout(pnlAssentosLayout);
        pnlAssentosLayout.setHorizontalGroup(
            pnlAssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAssentosLayout.setVerticalGroup(
            pnlAssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        btnComprar.setText("Comprar");
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprarMouseExited(evt);
            }
        });
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSessaoLayout = new javax.swing.GroupLayout(pnlSessao);
        pnlSessao.setLayout(pnlSessaoLayout);
        pnlSessaoLayout.setHorizontalGroup(
            pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSessaoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnlAssentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSessaoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSessaoLayout.createSequentialGroup()
                                .addComponent(checkDub)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(pnlSessaoLayout.createSequentialGroup()
                                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSessaoLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSessaoLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))
                                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSessaoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSessaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprar)
                        .addGap(136, 136, 136))))
            .addGroup(pnlSessaoLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSessaoLayout.setVerticalGroup(
            pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSessaoLayout.createSequentialGroup()
                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSessaoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSessaoLayout.createSequentialGroup()
                                .addComponent(checkDub)
                                .addGap(18, 18, 18)
                                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar))
                    .addGroup(pnlSessaoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(pnlAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        btnProcurar.setText("Procurar");
        btnProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcurarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcurarMouseExited(evt);
            }
        });
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        COFimgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        COFimgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        btnVoltar1.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar1.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFilmesLayout = new javax.swing.GroupLayout(pnlFilmes);
        pnlFilmes.setLayout(pnlFilmesLayout);
        pnlFilmesLayout.setHorizontalGroup(
            pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilmesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilmesLayout.createSequentialGroup()
                        .addComponent(btnVoltar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(COFimgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(pnlFilmesLayout.createSequentialGroup()
                        .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlFilmesLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnlFilmesLayout.createSequentialGroup()
                        .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlFilmesLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFilmesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(cmbSessoes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcurar)
                        .addGap(148, 148, 148))))
            .addGroup(pnlFilmesLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );
        pnlFilmesLayout.setVerticalGroup(
            pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilmesLayout.createSequentialGroup()
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(COFimgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFilmesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFilme)
                .addGap(22, 22, 22)
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilmesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(102, 102, 102)
                        .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSessoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcurar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(pnlSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        int idx = cmbSessoes.getSelectedIndex();
        String txt = cmbSessoes.getItemAt(idx);

        if(txt.equals("Selecione uma Sessão")){
            JOptionPane.showMessageDialog(null, "Selecione uma Sessão válida", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            btnComprar.setVisible(true);
            for (int i = 0; i < listaSessoes.size(); i++) {
                Sessao sess = listaSessoes.get(i);
                if(Objects.equals(listaSessoes.get(i).getFilmeId(), filme.getId()) && listaSessoes.get(i).getData().equals(txt)){

                    txtData.setText(txt);
                    txtPreco.setText(Double.toString(sess.getPreco()));
                    txtSala.setText(Integer.toString(sess.getSala()));
                    if(sess.isDub()){
                        checkDub.setSelected(true);
                    }else{
                        checkDub.setSelected(false);
                    }

                }
                
                
            }
        }
        
        // Insere os assentos
        
        for(int i=0; i<listaSessoes.size();i++){
            Sessao sess = listaSessoes.get(i);
            
            if(Objects.equals(sess.getFilmeId(), filme.getId()) && sess.getData().equals(txt)){
                List<Boolean> listaAssentos = sess.getAssentos();
                
                int x = 0;
                int y = 35;
                boolean pulou=false;
                for(int j=1; j<=90; j++){
                    
                    // Calcula as coordenadas
                    
                    // Pula Linha
                    
                    if(j%15==0){
                        x+=20;
                        pulou=true;
                        final JLabel labelAssento = new JLabel();
                        if(listaAssentos.get(j-1)==false){
                            labelAssento.setIcon(new ImageIcon("src/imagens/assentoazul.png")); 
                        }else{
                            labelAssento.setIcon(new ImageIcon("src/imagens/assentovermelho.png")); 
                        }
                        
                        labelAssento.setBounds(x, y, 16, 16);
                        
                        if(!listaAssentos.get(j-1)){
                            final int idxassento = j-1;
                            labelAssento.addMouseListener(new java.awt.event.MouseAdapter() {
                                 @Override
                                 public void mouseClicked(java.awt.event.MouseEvent evt) {
                                    final String imagem;
                                    if(listaSelected.get(idxassento)){
                                        imagem = "src/imagens/assentoazul.png";
                                        listaSelected.set(idxassento, false);
                                    }else{
                                        imagem = "src/imagens/assentolaranja.png";
                                        listaSelected.set(idxassento, true);
                                    }  
                                     labelAssento.setIcon(new ImageIcon(imagem)); 
                                 }
                             }); 
                        } 
                        
                        pnlAssentos.add(labelAssento);
                        pnlAssentos.revalidate();
                        pnlAssentos.repaint();
                        
                    }else{
                        if(pulou){
                            x=20;
                            y+=25;
                            pulou=false;
                        }else{
                            x+=20;
                        }

                        JLabel labelAssento = new JLabel();
                        if(listaAssentos.get(j-1)==false){
                            labelAssento.setIcon(new ImageIcon("src/imagens/assentoazul.png")); 
                        }else{
                            labelAssento.setIcon(new ImageIcon("src/imagens/assentovermelho.png")); 
                        }
                        labelAssento.setBounds(x, y, 16, 16);
                        
                        
                        if(!listaAssentos.get(j-1)){
                            final int idxassento = j-1;
                            labelAssento.addMouseListener(new java.awt.event.MouseAdapter() {
                                 @Override
                                 public void mouseClicked(java.awt.event.MouseEvent evt) {
                                    final String imagem;
                                    if(listaSelected.get(idxassento)){
                                        imagem = "src/imagens/assentoazul.png";
                                        listaSelected.set(idxassento, false);
                                    }else{
                                        imagem = "src/imagens/assentolaranja.png";
                                        listaSelected.set(idxassento, true);
                                    }  
                                     labelAssento.setIcon(new ImageIcon(imagem)); 
                                    
                                 }
                             }); 
                        }     
                        
                        
                        pnlAssentos.add(labelAssento);
                        pnlAssentos.revalidate();
                        pnlAssentos.repaint();
                    }
                    
                    
                }
                
                
            }
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void checkDubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDubActionPerformed

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        boolean flag=false;
        ArrayList<String> selecionado = new ArrayList<String>();   
        
        for(int i=0; i<listaSelected.size(); i++){
            if(listaSelected.get(i)){
                selecionado.add(transformaAssento(i+1));
                flag = true;
            }
        }
        if(!flag){
            JOptionPane.showMessageDialog(null, "Selecione ao menos um assento", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            String assentos = "";
            for(String item: selecionado) {
                assentos+= item + " ";
            }
            
            new TelaCompra(this, assentos, cmbSessoes.getSelectedIndex()-1, selecionado.size()).setVisible(true);
            dispose();
        } 
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnProcurarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarMouseEntered
        btnProcurar.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_btnProcurarMouseEntered

    private void btnProcurarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarMouseExited
        btnProcurar.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnProcurarMouseExited

    private void btnComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseEntered
        btnComprar.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_btnComprarMouseEntered

    private void btnComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseExited
        btnComprar.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnComprarMouseExited

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

       
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COFimgLogo;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JCheckBox checkDub;
    private javax.swing.JComboBox<String> cmbSessoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilme;
    private javax.swing.JPanel pnlAssentos;
    private javax.swing.JPanel pnlFilmes;
    private javax.swing.JPanel pnlSessao;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextArea txtSinopse;
    // End of variables declaration//GEN-END:variables
}
